DROP TABLE IF EXISTS student;

CREATE TABLE student (
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
	age INT(2) NULL DEFAULT NULL COMMENT '年龄',
	email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
	create_time datetime DEFAULT CURRENT_TIMESTAMP COMMENT '添加日期',
	is_delete INT(2) NOT NULL DEFAULT 0 COMMENT '是否删除',
	PRIMARY KEY (id)
);

/** 逻辑删除测试 */

DROP TABLE IF EXISTS common;
DROP TABLE IF EXISTS null1;
DROP TABLE IF EXISTS null2;

CREATE TABLE common(
    id      BIGINT(20) NOT NULL,
    name    VARCHAR(20) NOT NULL,
    deleted INT(11) NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE TABLE null1(
    id      BIGINT(20) NOT NULL,
    name    VARCHAR(20) NOT NULL,
    deleted INT(11),
    PRIMARY KEY (id)
);

CREATE TABLE null2(
    id       BIGINT(20) NOT NULL,
    name     VARCHAR(20) NOT NULL,
    del_time TIMESTAMP,
    PRIMARY KEY (id)
);