
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: tingfeng
    password: tingfeng

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.helijia.module.*.entity

