
# 数据源
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    url: jdbc:p6spy:h2:mem:test
    username: root
    password: test

  # 日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# MybatisPlus
mybatis-plus:
  type-enums-package: com.helijia.quickstart.common.enums

# 日志
logging:
  level:
    com.helijia.quickstart: debug

